### ISSUE TITLE
Heatbeat (BEAT) issues

### ISSUE THREAD

**Issue by cjbottaro** [contribsys/faktory#37]
My worker processes persist in the web UI despite having been stopped for hours.

Also, the signals do not persist.  For example, when I hit the `quiet` button in the UI, then the next BEAT response will report `quiet`, but any subsequent BEATs revert back to `ok` despite the UI still showing it's quiet.

Here's a screenshot:  http://storage.stochasticbytes.com.s3.amazonaws.com/4KIdyMeh.png

:v:

**Comment by mperham** [comment]
Fixed here: https://github.com/contribsys/faktory/commit/624ec2e5e2989aeaee2cc894f90db664aaaad82e#diff-2fb78608c50045336b8d076ac78cceb2L257

* A worker process should never stop BEATing.
* Worker processes will appear on the Busy page as long as they are BEATing, even if they are quiet and not processing jobs anymore.
* There's no way for a process to remove itself from that page, it must stop BEATing (due to process exit) and will be reaped after the 60 second timeout.

Let me know if you see behavior that violates those rules.

**Comment by cjbottaro** [comment]
Still seeing the issue...
1. pulled master
1. rebuilt Docker image
1. recreated Docker container
1. Started Elixir process to enqueue jobs (client connections still currently register as workers)
1. Exited Elixir process
1. After 5 minutes, the process still shows in Faktory UI

Faktory logs...
```
$ docker logs faktoryworkerex_dev_1
Faktory 0.5.0
Copyright © 2017 Contributed Systems LLC
Licensed under the GNU Public License 3.0
time="2017-10-28T21:14:40.858561Z" level=debug msg="Options{:7419 development /root/.faktory debug /root/.faktory/db true }"
time="2017-10-28T21:14:40.8587569Z" level=debug msg="Booting the en locale"
time="2017-10-28T21:14:40.8589231Z" level=debug msg="Initialized 26 locales"
time="2017-10-28T21:14:40.858951Z" level=info msg="Initializing storage at /root/.faktory/db"
time="2017-10-28T21:14:40.8589708Z" level=debug msg="Using RocksDB v5.7.3"
time="2017-10-28T21:14:40.8999651Z" level=info msg="Now listening at :7419, press Ctrl-C to stop"
time="2017-10-28T21:14:40.9000442Z" level=info msg="Web server now listening on port 7420"
time="2017-10-28T21:14:52.9816362Z" level=info msg="GET /queues 281.2µs"
time="2017-10-28T21:15:04.6613303Z" level=debug msg="&{Hostname:kaby Wid:7fbd520f84288d39 Pid:47576 Labels:[elixir] Salt: PasswordHash: StartedAt:2017-10-28 21:15:04.6612556 +0000 UTC m=+23.804638300 lastHeartbeat:{wall:13723975177873296304 ext:23804676600 loc:0xf5b920} state:0}"
time="2017-10-28T21:15:04.6613584Z" level=debug msg="&{Hostname:kaby Wid:7fbd520f84288d39 Pid:47576 Labels:[elixir] Salt: PasswordHash: StartedAt:2017-10-28 21:15:04.6612556 +0000 UTC m=+23.804638300 lastHeartbeat:{wall:13723975177873336404 ext:23804717800 loc:0xf5b920} state:0}"
time="2017-10-28T21:15:04.6613743Z" level=debug msg="&{Hostname:kaby Wid:7fbd520f84288d39 Pid:47576 Labels:[elixir] Salt: PasswordHash: StartedAt:2017-10-28 21:15:04.6612556 +0000 UTC m=+23.804638300 lastHeartbeat:{wall:13723975177873364004 ext:23804744200 loc:0xf5b920} state:0}"
time="2017-10-28T21:15:04.6613303Z" level=debug msg="&{Hostname:kaby Wid:7fbd520f84288d39 Pid:47576 Labels:[elixir] Salt: PasswordHash: StartedAt:2017-10-28 21:15:04.6612556 +0000 UTC m=+23.804638300 lastHeartbeat:{wall:13723975177873296304 ext:23804676600 loc:0xf5b920} state:0}"
time="2017-10-28T21:15:04.6615166Z" level=debug msg="&{Hostname:kaby Wid:7fbd520f84288d39 Pid:47576 Labels:[elixir] Salt: PasswordHash: StartedAt:2017-10-28 21:15:04.6612556 +0000 UTC m=+23.804638300 lastHeartbeat:{wall:13723975177873499004 ext:23804881300 loc:0xf5b920} state:0}"
time="2017-10-28T21:15:06.8696121Z" level=debug msg="Queue init: default 0 elements, 0/0"
time="2017-10-28T21:15:08.8270962Z" level=info msg="GET /queues 286.8µs"
time="2017-10-28T21:15:10.979553Z" level=info msg="GET /busy 379.3µs"
time="2017-10-28T21:15:15.9011465Z" level=info msg="GET /busy 304.7µs"
time="2017-10-28T21:16:10.3986266Z" level=info msg="GET /busy 314.3µs"
time="2017-10-28T21:16:11.7175683Z" level=info msg="GET /busy 328.6µs"
time="2017-10-28T21:16:16.3567612Z" level=info msg="GET /busy 309.1µs"
time="2017-10-28T21:16:17.0385845Z" level=info msg="GET /busy 277.7µs"
time="2017-10-28T21:16:17.9019219Z" level=info msg="GET /busy 311.3µs"
time="2017-10-28T21:16:18.4884771Z" level=info msg="GET /busy 215.3µs"
time="2017-10-28T21:16:19.4577556Z" level=info msg="GET /busy 221.4µs"
time="2017-10-28T21:16:20.5505308Z" level=info msg="GET /busy 331.2µs"
time="2017-10-28T21:16:21.3839732Z" level=info msg="GET /busy 388.6µs"
time="2017-10-28T21:17:21.9321848Z" level=info msg="GET /busy 260.3µs"
time="2017-10-28T21:17:22.7742447Z" level=info msg="GET /busy 367µs"
time="2017-10-28T21:17:23.4184192Z" level=info msg="GET /busy 282.1µs"
time="2017-10-28T21:19:02.3778764Z" level=info msg="GET /busy 292µs"
time="2017-10-28T21:19:03.189322Z" level=info msg="GET /busy 438.4µs"
time="2017-10-28T21:19:03.7748757Z" level=info msg="GET /busy 206.9µs"
```

Faktory UI:
http://storage.stochasticbytes.com.s3.amazonaws.com/wT3H0Vj1.png

**Comment by cjbottaro** [comment]
I thought what the issue may be is that these "client" connections are never sending a BEAT at all, so the reaping system is never "initialized" on the Faktory server.

But I just confirmed that the same issue happens with "worker" connections that have sent several successful BEATs.

**Comment by mperham** [comment]
Yep, just realized the job reaper is running (to re-enqueue jobs which aren't finished by crashed workers) but the beat reaper was never run.  On it now.

**Comment by mperham** [comment]
ok, should be better now, thanks for the double check.

**Comment by cjbottaro** [comment]
Awesome, works now!
